[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.21.2"
chrono = { version = "0.4.26", features = ["serde"] }
clap = { version = "4.3.11", features = ["derive"] }
colored = "2.0.4"
lazy_static = "1.4.0"
log = "0.4.19"
log4rs = "1.2.0"
mobc = "0.8.1"
mobc-redis = "0.8.0"
rand = "0.8.5"
redis = { version = "0.23.0", features = ["r2d2"] }
regex = "1.9.1"
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.102"
toml = "0.7.6"
