[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3.1"
common = { path = "../common" }
mail = { path = "../mail" }
serde = { version = "1.0.171", features = ["derive"] }
log = "0.4.19"
log4rs = "1.2.0"
clap = { version = "4.3.11", features = ["derive"] }
toml = "0.7.6"
actix-server = "2.2.0"
anyhow = "1.0.72"
redis = { version = "0.23.0", features = ["json", "tokio-comp", "connection-manager"] }
