[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.11", features = ["derive"] }
colored = "2.0.4"
log = "0.4.19"
log4rs = "1.2.0"
redis = "0.23.0"
rocket = { version = "0.5.0-rc.3", features = ["json"] }
serde = "1.0.171"
serde_json = "1.0.102"
