[package]
name = "mail"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
actix-web = "4.3.1"
log = "0.4.19"
serde = { version = "1.0.173", features = ["derive"] }
redis = { version = "0.23.0", features = ["json", "tokio-comp", "connection-manager"] }
